#!/bin/bash

src_dir=`pwd`

cd ${src_dir}/bundle
git clone git@github.com:VundleVim/Vundle.vim.git 
git clone --recurse-submodules git@github.com:ycm-core/YouCompleteMe.git
git clone git@github.com:SirVer/ultisnips.git  
git clone git@github.com:honza/vim-snippets.git
git clone git@github.com:volca/markdown-preview.git 
git clone git@github.com:vim-scripts/minibufexpl.vim.git  
git clone git@github.com:altercation/vim-colors-solarized.git  
git clone git@github.com:vim-latex/vim-latex.git  
git clone git@github.com:xuhdev/vim-latex-live-preview.git 
git clone git@github.com:preservim/vim-markdown.git  
git clone git@github.com:vim-syntastic/syntastic.git
git clone git@github.com:preservim/nerdtree.git
git clone git@github.com:vim-airline/vim-airline.git
git clone git@github.com:vim-airline/vim-airline-themes
git clone git@github.com:tpope/vim-fugitive
git clone --recursive git@github.com:davidhalter/jedi-vim.git 
git clone git@github.com:tpope/vim-projectionist.git


cd YouCompleteMe
git submodule update --init --recursive




